version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: sql-postgres
    command: >
      bash -c "ln -snf /usr/share/zoneinfo/Asia/Ho_Chi_Minh /usr/share/zoneinfo/Asia/Saigon && exec docker-entrypoint.sh postgres"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Ho_Chi_Minh
      PGTZ: Asia/Ho_Chi_Minh
    env_file:
      .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - sql-pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./server
    container_name: sql-backend
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - ./server/.env
    depends_on:
      - postgres

  frontend:
    build: ./client
    container_name: sql-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend

volumes:
  sql-pgdata:
